# Generated by Django 4.2 on 2023-05-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.SmallIntegerField()),
                ('image', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=120)),
                ('expiry', models.DateField()),
            ],
        ),
    ]
